import { supabase } from "./supabase";
import type { Participant } from "../types";

export interface RegistrationData {
    name: string;
    registerNumber: string;
    departmentId: string;
    batchId: string;
    gender: "male" | "female";
    semester: number;
}

/**
 * Registers a new participant.
 * Relies on Database constraints for uniqueness and sequences for chest number.
 */
export async function registerParticipant(data: RegistrationData): Promise<Participant> {

    // 1. Validate input
    if (!data.name || !data.registerNumber || !data.departmentId) {
        throw new Error("Missing required fields: Name, Register Number, or Department.");
    }

    const regNum = data.registerNumber.toUpperCase().trim();

    try {
        const { data: participantData, error } = await supabase
            .from('participants')
            .insert([
                {
                    name: data.name,
                    register_number: regNum,
                    department_id: data.departmentId,
                    batch_id: data.batchId,
                    gender: data.gender,
                    semester: data.semester,
                    // chest_number is auto-generated by sequence default
                    // total_points, individual_wins have defaults
                }
            ])
            .select()
            .single();

        if (error) {
            // Check for unique violation code (23505 is standard Postgres unique violation)
            if (error.code === '23505') {
                throw new Error(`Participant with Register Number ${regNum} already exists.`);
            }
            throw error;
        }

        // Map snake_case DB response to camelCase TS interface
        return {
            id: participantData.id,
            registerNumber: participantData.register_number,
            name: participantData.name,
            departmentId: participantData.department_id,
            batchId: participantData.batch_id,
            semester: participantData.semester,
            gender: participantData.gender,
            chestNumber: participantData.chest_number,
            totalPoints: participantData.total_points,
            individualWins: participantData.individual_wins,
        };

    } catch (e: any) {
        console.error("Error registering participant:", e);
        throw e;
    }
}
